### ISSUE TITLE
请问能提供一下预训练模型vgg嘛，我在网上下载的用不了

### ISSUE THREAD

**Issue by lyccol** [blanclist/CDNet#4]
Traceback (most recent call last):
  File "train.py", line 83, in <module>
    pin=False)
  File "/root/Documents/CDNet-train/code/solver.py", line 25, in train
    self.net.vgg_rgb.vgg.load_state_dict(torch.load(vgg_path))
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ModuleList:
	Unexpected key(s) in state_dict: "31.weight", "31.bias", "33.weight", "33.bias".

**Comment by blanclist** [comment]
> Traceback (most recent call last):
> File "train.py", line 83, in
> pin=False)
> File "/root/Documents/CDNet-train/code/solver.py", line 25, in train
> self.net.vgg_rgb.vgg.load_state_dict(torch.load(vgg_path))
> File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for ModuleList:
> Unexpected key(s) in state_dict: "31.weight", "31.bias", "33.weight", "33.bias".

您好，您尝试下能不能从下面的百度云盘链接下载，提取码是 "j0zq"：
https://pan.baidu.com/s/1kAh7FAUPuVLI5cvtBsxh-A
